### ISSUE TITLE
mobilePayload?

### ISSUE THREAD

**Issue by donavanbecker** [JOHNEPPILLAR/arlo#9]
can you post an example of what the mobilePayload looks like? I have tried to get the mobilePayload using HTTPCatcher and have never seen it.

**Comment by JOHNEPPILLAR** [comment]
When the mobile app checks for a valid sesion or requests an MFA token the body (json) contains an element called 'mobilePayload'. The structure is in the format of a the other tokens used by Arlo. It's a pain to re-engineer outside of intercepting the https payloads because of Cloudflare so using Postman is not an option.
